# Generated by Django 4.0.2 on 2022-04-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSN', models.CharField(max_length=10)),
                ('CNAME', models.TextField(max_length=50)),
                ('APT_NO', models.PositiveSmallIntegerField()),
                ('STREET_NO', models.PositiveSmallIntegerField()),
                ('CITY', models.TextField(max_length=50)),
                ('STATE', models.TextField(max_length=50)),
                ('ZIP', models.TextField(max_length=10)),
            ],
        ),
    ]
