# Generated by Django 4.0.2 on 2022-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_customer_city_alter_customer_cname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acc_No', models.PositiveIntegerField()),
                ('Balance', models.PositiveIntegerField()),
            ],
        ),
    ]
